name: Build & Commit

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm ci
      - name: Build Packages
        run: npm run build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: packages-build
          path: packages
  commit:
    name: Commit Packages
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: packages-build
          path: packages
      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=pkgsChanged::$(git diff --quiet HEAD -- packages; echo $?)"
      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ steps.vars.outputs.pkgsChanged == 1 }}
        with:
          commit_message: ${{ format('Update packages from @ {0} :rocket:', steps.vars.outputs.sha_short) }}

