name: Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm ci
      - name: Build Packages
        run: npm run build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: packages-build
          path: packages
  publish:
    name: Publish Packages
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: packages-build
          path: packages
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check Changes (vue-heroicons)
        uses: marceloprado/has-changed-path@v1
        id: vueHeroiconsChanged
        with:
          paths: packages/vue-heroicons
      - name: Bump Version (vue-heroicons)
        if: ${{ steps.vueHeroiconsChanged.outputs.changed == 1 }}
        run: npm version minor
        working-directory: packages/vue-heroicons
      - name: Publish Package (vue-heroicons)
        uses: JS-DevTools/npm-publish@v1
        if: ${{ steps.vueHeroiconsChanged.outputs.changed == 1 }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
        working-directory: packages/vue-heroicons
      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ steps.vueHeroiconsChanged.outputs.changed == 1 }}
        with:
          commit_message: ${{ format('Update packages from @ {0} :rocket:', steps.vars.outputs.sha_short) }}

