name: Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm ci
      - name: Show Aggregate Checksums (Pre-Build)
        run: |
          echo packages/vue-heroicons: "find packages/vue-heroicons -type f -print0 | sort -z | xargs -0 sha1sum | sha1sum | awk '{ print $1 }'"
      - name: Build Packages
        run: npm run build
      - name: Show Aggregate Checksums (Post-Build)
        run: |
          echo packages/vue-heroicons: "find packages/vue-heroicons -type f -print0 | sort -z | xargs -0 sha1sum | sha1sum | awk '{ print $1 }'"
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: packages-build
          path: packages
  publish:
    name: Publish Packages
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: packages-build
          path: packages
      - name: Set Variables
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=vueChanged::$(git diff --quiet HEAD -- packages/vue-heroicons; echo $?)"
      - name: Publish vue-heroicons
        uses: JS-DevTools/npm-publish@v1
        if: ${{ steps.vars.outputs.vueChanged == 1 }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/vue-heroicons/package.json
          access: public
      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ steps.vars.outputs.vueChanged == 1 }}
        with:
          commit_message: ${{ format('Update packages from @ {0} :rocket:', steps.vars.outputs.sha_short) }}

